spring:
  config:
    activate:
      on-profile: secret-local
  datasource:
    url: jdbc:h2:mem:spring-boot-boilerplate;MODE=MySQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  data:
    redis:
      host: localhost
      port: 6379
      ssl:
        enabled: true
auth:
  jwt:
    secret: "a9e8f7g6h5i4j3k2l1m0n9o8p7q6r5s4t3u2v1w0x9y8z7"
    access-expire: 7200
    refresh-expire: 604800
  x-api-key: abcd1234-ef56-7890-ghij-1234567890kl

jwt-security:
  # The secret key used to sign JWT tokens.
  # This should be a secure, randomly generated value in production.
  secret: 09a9e6d1b49cd8911da9cf90dd85381be1968cbf72f5a14e335fad1d7352506f
  api-key: 1f242d49b9816078f71dbddc7240a8b64843
  # Defines the token expiration time in days. Here, it's set to 365 days.
  expiration-time: 365

cors:
  origin:
    frontend: http://localhost:8000