spring:
  profiles:
    active: local
    group:
      "local": "local, common, secret-local"
      "dev": "dev, common, secret-dev"
      "prod": "prod, common, secret-prod"

#---
#spring:
#  datasource:
#    password: erpspringkotlindb
#    username: erp_user
#    url: jdbc:mysql://host.docker.internal:3306/erp_db?ssl-mode=REQUIRED
#  config:
#    activate:
#      on-profile: docker
#server:
#  port: 8888
#  servlet:
#    context-path: /erp-test